name: password_hasher
version: 0.2.0
author: James Ots <code@jamesots.com>
homepage: https://github.com/jamesots/password_hasher
description: Utility for hashing passwords
dependencies:
  crypto: ">=1.0.0 <3.0.0"
  pbkdf2: 
    git: https://github.com/IOT-DSA/pbkdf2.git
dev_dependencies:
  unittest: ">=0.10.0 <0.11.0"
